export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum OrgPlan {
  FREE = 'FREE',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SubscriptionStatus {
  ACTIVE = 'active',
  TRIALING = 'trialing',
  PAST_DUE = 'past_due',
  CANCELED = 'canceled',
  INCOMPLETE = 'incomplete',
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum ProjectType {
  WEBSITE = 'WEBSITE',
  MOBILE_APP = 'MOBILE_APP',
  SAAS = 'SAAS',
  ECOMMERCE = 'ECOMMERCE',
  BLOG = 'BLOG',
  OTHER = 'OTHER',
}

export enum SocialPlatform {
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  GOOGLE = 'GOOGLE',
  TELEGRAM = 'TELEGRAM',
  GOOGLE_PLAY = 'GOOGLE_PLAY',
}

export enum CampaignType {
  EMAIL = 'EMAIL',
  SOCIAL = 'SOCIAL',
  BLOG = 'BLOG',
  MULTI_CHANNEL = 'MULTI_CHANNEL',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
}

export enum ContentType {
  SOCIAL_POST = 'SOCIAL_POST',
  BLOG_ARTICLE = 'BLOG_ARTICLE',
  EMAIL = 'EMAIL',
  NEWSLETTER = 'NEWSLETTER',
  AD_COPY = 'AD_COPY',
  LANDING_PAGE = 'LANDING_PAGE',
  SEO_ARTICLE = 'SEO_ARTICLE',
  REFERRAL_COPY = 'REFERRAL_COPY',
  IN_APP_MESSAGE = 'IN_APP_MESSAGE',
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  REVIEW = 'REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
}

export enum EmailProvider {
  SMTP = 'SMTP',
  RESEND = 'RESEND',
}

export enum EmailAccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ERROR = 'ERROR',
}

export enum EmailSubscriberStatus {
  ACTIVE = 'ACTIVE',
  UNSUBSCRIBED = 'UNSUBSCRIBED',
  BOUNCED = 'BOUNCED',
}

export enum ChecklistType {
  LAUNCH = 'LAUNCH',
  WEEKLY = 'WEEKLY',
  CAMPAIGN_PREP = 'CAMPAIGN_PREP',
  SEO = 'SEO',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  EMAIL_CAMPAIGN = 'EMAIL_CAMPAIGN',
  COMPETITIVE_ANALYSIS = 'COMPETITIVE_ANALYSIS',
  CUSTOM = 'CUSTOM',
  PRODUCT_HUNT_LAUNCH = 'PRODUCT_HUNT_LAUNCH',
}

export enum ChecklistItemPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AgentType {
  STRATEGY = 'STRATEGY',
  CONTENT = 'CONTENT',
  SEO = 'SEO',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  EMAIL = 'EMAIL',
  ANALYTICS = 'ANALYTICS',
  CHECKLIST = 'CHECKLIST',
  DOCUMENT = 'DOCUMENT',
  SUPERVISOR = 'SUPERVISOR',
}

export enum AgentRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AnalyticsEventType {
  PAGE_VIEW = 'PAGE_VIEW',
  EMAIL_OPEN = 'EMAIL_OPEN',
  EMAIL_CLICK = 'EMAIL_CLICK',
  SOCIAL_ENGAGEMENT = 'SOCIAL_ENGAGEMENT',
  CONVERSION = 'CONVERSION',
  SIGNUP = 'SIGNUP',
  TRIAL_START = 'TRIAL_START',
  ACTIVATION = 'ACTIVATION',
  UPGRADE = 'UPGRADE',
  CHURN = 'CHURN',
  FUNNEL_STEP = 'FUNNEL_STEP',
}

export enum ABTestStatus {
  DRAFT = 'DRAFT',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
}

export enum ABTestType {
  EMAIL_SUBJECT = 'EMAIL_SUBJECT',
  CONTENT_VARIANT = 'CONTENT_VARIANT',
  LANDING_PAGE = 'LANDING_PAGE',
}

export enum EmailSequenceTrigger {
  SIGNUP = 'SIGNUP',
  MANUAL = 'MANUAL',
  EVENT = 'EVENT',
  DATE = 'DATE',
}

export enum EmailSequenceStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
}

export enum EnrollmentStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  PAUSED = 'PAUSED',
  UNSUBSCRIBED = 'UNSUBSCRIBED',
}

export enum KeywordIntent {
  INFORMATIONAL = 'INFORMATIONAL',
  NAVIGATIONAL = 'NAVIGATIONAL',
  COMMERCIAL = 'COMMERCIAL',
  TRANSACTIONAL = 'TRANSACTIONAL',
}

export enum EntityScope {
  PROJECT = 'PROJECT',
  ORGANIZATION = 'ORGANIZATION',
}

export enum EntityLinkType {
  COPY = 'COPY',
  LINK = 'LINK',
}

export enum EntityModelType {
  CONTENT = 'CONTENT',
  CHECKLIST = 'CHECKLIST',
  DOCUMENT = 'DOCUMENT',
  CAMPAIGN = 'CAMPAIGN',
  EMAIL_LIST = 'EMAIL_LIST',
  KEYWORD = 'KEYWORD',
  COMPETITOR = 'COMPETITOR',
  ANALYTICS_EVENT = 'ANALYTICS_EVENT',
  AB_TEST = 'AB_TEST',
  EMAIL_SEQUENCE = 'EMAIL_SEQUENCE',
}

export enum GoogleIntegrationType {
  SEARCH_CONSOLE = 'SEARCH_CONSOLE',
  ANALYTICS = 'ANALYTICS',
  PLAY_CONSOLE = 'PLAY_CONSOLE',
}
