import { Test, TestingModule } from '@nestjs/testing';
import { BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GooglePlayAuthService } from './google-play-auth.service';
import { GooglePlayMetricsService } from './google-play-metrics.service';
import { PrismaService } from '../database/prisma.service';

const mockPrisma = {
  projectApiKey: {
    findUnique: jest.fn(),
    upsert: jest.fn(),
    deleteMany: jest.fn(),
    update: jest.fn(),
  },
  appStoreMetrics: {
    findMany: jest.fn(),
    deleteMany: jest.fn(),
  },
  appReview: {
    deleteMany: jest.fn(),
  },
  project: {
    findUnique: jest.fn(),
  },
};

const mockConfig = {
  get: jest.fn((key: string, def?: string) => {
    const map: Record<string, string> = {
      GOOGLE_CLIENT_ID: 'test-client-id',
      GOOGLE_CLIENT_SECRET: 'test-secret',
      ENCRYPTION_KEY: 'ab'.repeat(32), // valid 64-char hex = 32 bytes
      API_URL: 'http://localhost:3000',
    };
    return map[key] || def || '';
  }),
};

describe('GooglePlayAuthService', () => {
  let service: GooglePlayAuthService;

  beforeEach(async () => {
    jest.clearAllMocks();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        GooglePlayAuthService,
        { provide: PrismaService, useValue: mockPrisma },
        { provide: ConfigService, useValue: mockConfig },
      ],
    }).compile();
    service = module.get<GooglePlayAuthService>(GooglePlayAuthService);
  });

  describe('getAuthUrl', () => {
    it('returns a valid OAuth2 URL containing androidpublisher scope', () => {
      const url = service.getAuthUrl('project-123');

      expect(url).toContain('https://accounts.google.com/o/oauth2/v2/auth');
      expect(url).toContain('androidpublisher');
      expect(url).toContain('playdeveloperreporting');
      expect(url).toContain('client_id=test-client-id');
      expect(url).toContain('state=');
    });
  });

  describe('verifyState', () => {
    it('correctly verifies a state parameter generated by getAuthUrl', () => {
      const url = service.getAuthUrl('project-456');
      const parsedUrl = new URL(url);
      const state = parsedUrl.searchParams.get('state')!;

      const projectId = service.verifyState(state);
      expect(projectId).toBe('project-456');
    });

    it('throws BadRequestException on tampered state', () => {
      // Build a state with a valid structure but wrong HMAC
      const payload = 'project-789:' + Date.now();
      const fakeHmac = 'a'.repeat(64); // wrong HMAC, but same length as a real sha256 hex
      const tampered = Buffer.from(`${payload}:${fakeHmac}`).toString('base64url');

      expect(() => service.verifyState(tampered)).toThrow(BadRequestException);
    });
  });

  describe('saveServiceAccountConfig', () => {
    it('throws on invalid JSON', async () => {
      await expect(
        service.saveServiceAccountConfig('proj-1', 'not-json', 'com.example'),
      ).rejects.toThrow(BadRequestException);
      await expect(
        service.saveServiceAccountConfig('proj-1', 'not-json', 'com.example'),
      ).rejects.toThrow('Invalid service account JSON');
    });

    it('throws on JSON missing required fields (client_email, private_key)', async () => {
      const incomplete = JSON.stringify({ type: 'service_account' });
      await expect(
        service.saveServiceAccountConfig('proj-1', incomplete, 'com.example'),
      ).rejects.toThrow(BadRequestException);
      await expect(
        service.saveServiceAccountConfig('proj-1', incomplete, 'com.example'),
      ).rejects.toThrow('client_email and private_key');
    });

    it('saves valid config and calls prisma upsert', async () => {
      mockPrisma.projectApiKey.upsert.mockResolvedValue({});

      const validKey = JSON.stringify({
        type: 'service_account',
        client_email: 'test@gserviceaccount.com',
        private_key: '-----BEGIN RSA PRIVATE KEY-----\nfake\n-----END RSA PRIVATE KEY-----',
      });

      await service.saveServiceAccountConfig('proj-1', validKey, 'com.example.app');

      expect(mockPrisma.projectApiKey.upsert).toHaveBeenCalledTimes(1);
      const call = mockPrisma.projectApiKey.upsert.mock.calls[0][0];
      expect(call.where.projectId_platform).toEqual({
        projectId: 'proj-1',
        platform: 'GOOGLE_PLAY',
      });
      expect(call.create.projectId).toBe('proj-1');
      expect(call.create.platform).toBe('GOOGLE_PLAY');
      expect(call.create.encryptedKey).toBeTruthy();
      expect(call.create.scopes).toEqual(['androidpublisher', 'playdeveloperreporting']);
    });
  });

  describe('disconnect', () => {
    it('deletes api key and data when deleteData is true', async () => {
      mockPrisma.projectApiKey.deleteMany.mockResolvedValue({ count: 1 });
      mockPrisma.appStoreMetrics.deleteMany.mockResolvedValue({ count: 5 });
      mockPrisma.appReview.deleteMany.mockResolvedValue({ count: 3 });

      await service.disconnect('proj-1', true);

      expect(mockPrisma.projectApiKey.deleteMany).toHaveBeenCalledWith({
        where: { projectId: 'proj-1', platform: 'GOOGLE_PLAY' },
      });
      expect(mockPrisma.appStoreMetrics.deleteMany).toHaveBeenCalledWith({
        where: { projectId: 'proj-1' },
      });
      expect(mockPrisma.appReview.deleteMany).toHaveBeenCalledWith({
        where: { projectId: 'proj-1' },
      });
    });

    it('keeps data when deleteData is false', async () => {
      mockPrisma.projectApiKey.deleteMany.mockResolvedValue({ count: 1 });

      await service.disconnect('proj-1', false);

      expect(mockPrisma.projectApiKey.deleteMany).toHaveBeenCalledTimes(1);
      expect(mockPrisma.appStoreMetrics.deleteMany).not.toHaveBeenCalled();
      expect(mockPrisma.appReview.deleteMany).not.toHaveBeenCalled();
    });
  });
});

describe('GooglePlayMetricsService', () => {
  let service: GooglePlayMetricsService;

  beforeEach(async () => {
    jest.clearAllMocks();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        GooglePlayMetricsService,
        { provide: PrismaService, useValue: mockPrisma },
      ],
    }).compile();
    service = module.get<GooglePlayMetricsService>(GooglePlayMetricsService);
  });

  describe('getMetrics', () => {
    it('calls prisma with correct date range', async () => {
      mockPrisma.appStoreMetrics.findMany.mockResolvedValue([]);

      await service.getMetrics('proj-1', '2026-01-01', '2026-01-31');

      expect(mockPrisma.appStoreMetrics.findMany).toHaveBeenCalledWith({
        where: {
          projectId: 'proj-1',
          date: {
            gte: new Date('2026-01-01'),
            lte: new Date('2026-01-31'),
          },
        },
        orderBy: { date: 'asc' },
      });
    });
  });

  describe('getMetricsTotals', () => {
    it('returns correct structure with trends', async () => {
      const currentRows = [
        {
          installs: 100,
          uninstalls: 10,
          activeDeviceInstalls: 500,
          storeListingVisitors: 1000,
          crashes: 5,
          anrs: 2,
          crashRate: 0.01,
          anrRate: 0.004,
          averageRating: 4.5,
          totalRatings: 200,
          revenue: 99.99,
        },
      ];
      const previousRows = [
        {
          installs: 50,
          uninstalls: 5,
          activeDeviceInstalls: 400,
          storeListingVisitors: 800,
          crashes: 10,
          anrs: 4,
          crashRate: 0.02,
          anrRate: 0.008,
          averageRating: 4.0,
          totalRatings: 150,
          revenue: 50.0,
        },
      ];

      mockPrisma.appStoreMetrics.findMany
        .mockResolvedValueOnce(currentRows)
        .mockResolvedValueOnce(previousRows);

      const result = await service.getMetricsTotals('proj-1', 30);

      expect(result.installs).toBe(100);
      expect(result.uninstalls).toBe(10);
      expect(result.activeDeviceInstalls).toBe(500);
      expect(result.revenue).toBe(99.99);
      expect(result.previous).toBeDefined();
      expect(result.previous.installs).toBe(50);
      expect(result.changes).toBeDefined();
      expect(result.changes.installs.trend).toBe('up');
      expect(result.changes.installs.value).toBe(100); // (100-50)/50 * 100 = 100%
      expect(result.changes.crashes.trend).toBe('down'); // 5 vs 10 => -50%
    });

    it('handles empty data (no metrics in DB)', async () => {
      mockPrisma.appStoreMetrics.findMany
        .mockResolvedValueOnce([])
        .mockResolvedValueOnce([]);

      const result = await service.getMetricsTotals('proj-1', 30);

      expect(result.installs).toBe(0);
      expect(result.uninstalls).toBe(0);
      expect(result.activeDeviceInstalls).toBe(0);
      expect(result.storeListingVisitors).toBe(0);
      expect(result.storeListingConversions).toBe(0);
      expect(result.crashes).toBe(0);
      expect(result.revenue).toBe(0);
      expect(result.previous.installs).toBe(0);
      // All changes should be flat when both periods are 0
      expect(result.changes.installs.trend).toBe('flat');
      expect(result.changes.installs.value).toBe(0);
    });

    it('correctly computes storeListingConversions from totals (not sum of rates)', async () => {
      const currentRows = [
        {
          installs: 30,
          uninstalls: 2,
          activeDeviceInstalls: 100,
          storeListingVisitors: 200,
          crashes: 0,
          anrs: 0,
          crashRate: 0,
          anrRate: 0,
          averageRating: 4.0,
          totalRatings: 50,
          revenue: 0,
        },
        {
          installs: 70,
          uninstalls: 3,
          activeDeviceInstalls: 120,
          storeListingVisitors: 300,
          crashes: 0,
          anrs: 0,
          crashRate: 0,
          anrRate: 0,
          averageRating: 4.2,
          totalRatings: 55,
          revenue: 0,
        },
      ];

      mockPrisma.appStoreMetrics.findMany
        .mockResolvedValueOnce(currentRows)
        .mockResolvedValueOnce([]);

      const result = await service.getMetricsTotals('proj-1', 30);

      // Total installs = 30 + 70 = 100
      // Total visitors = 200 + 300 = 500
      // Conversion = (100 / 500) * 10000 / 100 = 20.00%
      expect(result.installs).toBe(100);
      expect(result.storeListingVisitors).toBe(500);
      expect(result.storeListingConversions).toBe(20);
    });
  });
});
